name: binary-orphans
version: 0.1.4.0
synopsis: Orphan instances for binary
description: |
  `binary-orphans` defines orphan instances for types in some popular packages.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/binary-orphans
category: Web
tested-with: GHC==7.6.3, GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options: -Wall -fno-warn-orphans

dependencies:
  - base                     >=4.6.0.1   && <4.9
  - aeson                    >=0.7.0.6   && <0.10.1 # Binary Value
  - binary                   >=0.5.1.1   && <0.8.1  # We define Binary instances
  - hashable                 >=1.2.3.3   && <1.3
  - scientific               >=0.3.3.8   && <0.4
  - semigroups               >=0.16.2.2  && <0.18.2 # Binary NonEmpty
  - tagged                   >=0.7.3     && <0.8.4  # Binary Tagged
  - text                     >=1.2.0.6   && <1.3
  - time                     >=1.4.0.1   && <1.6.1  # Binary UTCTime etc.
  - unordered-containers     >=0.2.5.1   && <0.3
  - vector                   >=0.10.12.3 && <0.12

library:
  source-dirs: src
  dependencies:
   - text-binary              >=0.1.0   && <0.3 # Unnecessary after text >=1.2.1
   - vector-binary-instances  >=0.2.1.0 && <0.3

tests:
  binary-orphans-test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary-orphans
      - quickcheck-instances >=0.3.11   && <0.4
      - tasty                >=0.10.1.2 && <0.12
      - tasty-quickcheck     >=0.8.3.2  && <0.9
