name: binary-orphans
version: 0.1.1.0
synopsis: Orphan instances for binary
description: |
  `binary-orphans` defines orphan instances for types in some popular packages.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/binary-orphans
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options: -Wall -fno-warn-orphans

dependencies:
  - base                     >=4.7  && <4.9
  - aeson                    >=0.8  && <0.11
  - binary                   >=0.7  && <0.8
  - hashable                 >=1.2  && <1.3
  - scientific               >=0.3  && <0.4
  - tagged                   >=0.7  && <0.9
  - text                     >=1.2  && <1.3
  - time                     >=1.4  && <1.6
  - unordered-containers     >=0.2  && <0.3
  - vector                   >=0.10 && <0.12

library:
  source-dirs: src
  dependencies:
   - text-binary              >=0.1  && <0.3 # Unnecessary after text >=1.2.1
   - vector-binary-instances  >=0.2  && <0.3

tests:
  binary-orphans-test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary-orphans
      - quickcheck-instances
      - tasty
      - tasty-quickcheck
