name: binary-orphans
version: 0.1.5.1
synopsis: Orphan instances for binary
description: |
  `binary-orphans` defines orphan instances for types in some popular packages.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/binary-orphans
category: Web
tested-with: GHC==7.6.3, GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options: -Wall -fno-warn-orphans

dependencies:
  - base                     >=4.6.0.1   && <4.10
  - aeson                    >=0.7.0.6   && <0.11.3 # Binary Value
  - binary                   >=0.5.1.1   && <0.8.5  # We define Binary instances
  - case-insensitive         >=1.2.0.4   && <1.2.1
  - hashable                 >=1.2.3.3   && <1.3
  - scientific               >=0.3.3.8   && <0.4
  - tagged                   >=0.7.3     && <0.8.5  # Binary Tagged
  - text                     >=1.2.0.6   && <1.3
  - time                     >=1.4.0.1   && <1.6.1  # Binary UTCTime etc.
  - unordered-containers     >=0.2.5.1   && <0.3
  - vector                   >=0.10.12.3 && <0.12

when:
  - condition: "!impl(ghc >= 8.0)"
    dependencies:
    - semigroups               >=0.16.2.2  && <0.18.2 # Binary NonEmpty
  - condition: "!impl(ghc >= 7.10)"
    dependencies:
    - void                     >=0.7       && <0.8
    - nats                     >=1         && <1.2

library:
  source-dirs: src
  dependencies:
   - text-binary              >=0.1.0   && <0.3 # Unnecessary after text >=1.2.1
   - vector-binary-instances  >=0.2.1.0 && <0.3

tests:
  binary-orphans-test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary-orphans
      - QuickCheck           >=2.7      && <2.9.2
      - quickcheck-instances >=0.3.11   && <0.3.13
      - tasty                >=0.10.1.2 && <0.12
      - tasty-quickcheck     >=0.8.3.2  && <0.9
